---
file_name: CHANGELOG.md
excluded_labels:
  - attention-needed
sections:
  added:
    - feature
    - enhancement
    - dependencies
  changed:
    - maintenance
    - backwards-incompatible
  fixed:
    - bug
    - bugfix
    - documentation
skip_entries_without_label: false
show_unreleased: true
check_for_updates: true
logger: spinner
