fixtures:
  repositories:
    "facts": "https://github.com/puppetlabs/puppetlabs-facts.git"
    "puppet_conf": "https://github.com/puppetlabs/puppetlabs-puppet_conf.git"
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.13.0
  symlinks:
    "provision": "#{source_dir}"
