---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  simplecov: true
  notifications:
    slack:
      secure: >-
        EYcrPlgOclhyT2cdNZpSyQOZiZvgj0WYDzD0dq248cpvoAlL/5GPXpttTaAy9k1pjWoGh5azNIn+hYGmuTMxMuAT2lHwDEQotXqrQVbphynMABu45GBiuAfO6uZPFgcQtDtKaax2TjEG8sK7xJw8FdhBo+YMpxSJHtgV7IjmYs0aU89gG4BGUSgULFf4kswPfu8IxNvgXUTipzeRQUg920arjXFSsjkiefirk71NUpzS6vR7Q4DXjtUKl9jWdu5soouTzwb4J11TfZz2RvN9lZw0fzDjVdWcye5SpRsnCvXKaNjoGyVWBMY2Zo1ThlrFHR1MECyyX8lwsSMz0Uyl6rhfF35W5Fzxo5M+U9d0ANifE9Ttcmxt8a8AYpaxxgWYwVRIzMequPBGHluv+52oQ5jrOsYduxdwagyuYdgBieNQrE3NTWTos9N5xk+QCVOBoKrwVqWKvA8ldduP0doXpQllHw6uI2KEI2eUvh2Tohzu2vnuurXEocJtm9H21qqQvthMAFPCNVlzw3rDaCax3Q65raWXq160riGp42B9rs/IBdlgXkbQpVvyh9/HMExv/3oWQMJqKGpSKNAfaTjpQ4D6CGAFWi63L+nDyENGMdFZ3cyEGc+Kmz3KOszJqKE3mK3r6SECCq+zgPLKz3K73ovx7u2yUMtLS5ebYKwn94w=
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      version: '= 1.15.2'
    - gem: webmock
Rakefile:
  changelog_project: provision
  default_disabled_lint_checks:
    - 140chars
spec/spec_helper.rb:
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
