name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    with:
      # This line enables shellcheck to be run on this repository
      run_shellcheck: true
    secrets: "inherit"
