name: "Release Prep"

on:
  workflow_dispatch:

jobs:
  release_prep:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_release_prep.yml@main"
    with:
      version: "${{ github.event.inputs.version }}"
    secrets: "inherit"
